name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
    - uses: actions/setup-node@v1.1.0
      with:
        version: 13.10.1
    - run: yarn
    - run: yarn build
